services:
  mysql-kpi:
    image: mysql:8.0
    container_name: mysql-ms-kpi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_kpi_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_kpi_data:/var/lib/mysql

volumes:
  mysql_kpi_data: